# 파이썬의 기본문법
## 인프런 프로그래밍 시작하기 : 파이썬 입문 (Inflearn Original)
## 상명대학교 김민정 교수님 python을 활용한 데이터 분석 따라하기

## 조건문과 반복문

### 조건문
    - 조건문과 반복문은 모든 언어에서 가장 기본이 되고 많이 사용하는 명령어
    - 특히, 최근 데이터 들이 big data화 됨에 따라 조건문과 반복문 등의 사용능력 중요
    - if,elif,else
### 논리연산
    - 조건문에 사용되는 조건의 경우 논리식 AND(and), OR(or), NOT(not)사용 가능
    - 우선순위:NOT>AND>OR


In [5]:
#if
if 5 >3 :
    print("True")
a=1
b=3
c=5
if a==1 and b==2:
    print("True")
if a==1 or b==2:
    print("True")
if a !=10: #!= not ==
    print("True")
if not a == 10: 
    print("True")

True
True
True
True


In [6]:
#if-else-elif
a = 11
if a % 4 ==0:
    print("a%4 is 0")
elif a % 4 ==1:
    print("a%4 is 1")
elif a % 4 ==2:
    print("a%4 is 2")
else:
    print("a%4 is 3")

a%4 is 3


In [7]:
#중첩 조건문
a = 10
b = 5

if a == 10:
    if b == 5:
        print("true, true")
    else:
        print("true, false")

true, true


In [9]:
#반복문 while -true면 실행 false면 건너 뜀 (사용시 무한루프를 조심해야함)
a = [1, 3, 9, 5]
i=0
while i < len(a):
    if a[i]>5:
        print("index:", i, "value:",a[i])
    i = i+1


index: 2 value: 9


In [10]:
#break
a= [1, 3, 9, 5]

i = 0 #익데스
while i < len(a):
    if a[i]>5:
        break
    print("index:", i, "value:",a[i])
    i = i+1

index: 0 value: 1
index: 1 value: 3


In [23]:
#중첩 가능 (구구단 만들기)
x=1
while x<=9:
    y=1
    while y<=9:
        print(x*y)
        y=y+1
    x=x+1

1
2
3
4
5
6
7
8
9
2
4
6
8
10
12
14
16
18
3
6
9
12
15
18
21
24
27
4
8
12
16
20
24
28
32
36
5
10
15
20
25
30
35
40
45
6
12
18
24
30
36
42
48
54
7
14
21
28
35
42
49
56
63
8
16
24
32
40
48
56
64
72
9
18
27
36
45
54
63
72
81


In [13]:
#반복문 for -순환하면서 값 처리(문자열, 튜플 ,리스트, 딕셔너리)
a =[1, 3, 9, 5]

for i in a:
    print(i)

1
3
9
5


In [15]:
#enumerate()함수로 인덱스와 값 모두 출력
a =[1, 3, 9, 5]

for index, num in enumerate(a):
    print("index:",index, num)


index: 0 1
index: 1 3
index: 2 9
index: 3 5


In [16]:
#딕셔너리도 사용 가능
a={"A:":"apple", "B":"banana","C":"carrot"}
for key, value in a.items():
    print(key, value)

A: apple
B banana
C carrot


In [17]:
#break:특정 조건일때 반복종료
a=[1, 3, 9, 5]
for num in a:
    if num> 5:
        break
        
    print(num)


1
3


In [21]:
#중첩 가능 (이용하여 구구단 만들기)
a=[1,2,3,4,5,6,7,8,9]
b=[1,2,3,4,5,6,7,8,9]
for i in a:
    for j in b:
        print(i*j)

1
2
3
4
5
6
7
8
9
2
4
6
8
10
12
14
16
18
3
6
9
12
15
18
21
24
27
4
8
12
16
20
24
28
32
36
5
10
15
20
25
30
35
40
45
6
12
18
24
30
36
42
48
54
7
14
21
28
35
42
49
56
63
8
16
24
32
40
48
56
64
72
9
18
27
36
45
54
63
72
81


# 함수:특정한 기능을 수행하는 명령어들의 모음

In [30]:
#내장함수
a =range(10) #내장함수 range 이용해 리스트 생성
b= sum(a) #sum() 이용해 리스트, 튜플등을 입력하여 전체 아이템의 합 출력 가능
print(b)
c= len(a) #len() 이용해 리스트,튜플 등을 입력으로 전달하면 아이템의 개수를 출력으로 전달
print(c)
#그 외 print(), type()
#max, min :최대값 최솟값
## id : 객체의 주소값(래퍼런스) 반환
# str(), int(), tuple() :문자열, 정수, 튜플 등 형변환
#abs():절대값 
# zip : 반복가능한 객체 (iterable)의 요소를 묶어서 반환 ->짝이 안맞으면 맞는 것만 반환하며 튜플로 반환


45
10


In [32]:
#def:함수 정의시 사용
def add(x,y): #x,y는 인자(미지수로서 향후 사용될 값을 담는 변수, 매개변수)
    result=x+y 
    return result #result는 반환값으로 함수 실행의 결과값을 의미 ,표시하려면 print()사용

In [33]:
print(add(1,5))

6


In [34]:
def say_hello(name, msg):
    print("Hello",name,msg)

In [35]:
name ="john"
msg ="hi"
say_hello(name,msg)

Hello john hi


# format 함수
여러가지 값과 포맷을 이용하여 문자열을 정의할 수 있는 함수 {} placeholder를 문자열 내에 위치 시킨 후, 해당위치에 format 함수로 전달된 값으로 대체하여 문자열 생성

In [2]:
temp =23
rain =30
a = "오늘 기온: {}도, 비올 확률 {}%".format(temp,rain)
print(a)

오늘 기온: 23도, 비올 확률 30%


- #### lamda 함수
- 단일문으로 표현되는 익명함수(이름x,구현체만 존재하는 간단한 함수를 의미)
- 코드 상에서 한번만 사용되는 기능이 있을 때, 굳이 함수로 만들지 않고 1회성으로 만들어서 쓸 때 사용

In [3]:
def add(x,y):
    result=x+y 
    return result

In [4]:
add2 =lambda x,y : x+y
add2(1,5)

6

# 모듈 
- 모듈이란 서로 관련이 있는 함수나 변수 또는 클래시 들을 모아 놓은 함수
- 이미 만들어진 것과, 본인이 만들어서 사용가능

In [6]:
#import 모듈 :모듈 불러오기
import math

In [7]:
#form 모듈 import 함수: 모듈내 필요한 함수만 불러오기
from math import pi

In [9]:
#import 모듈 as 별명: 모듈 불러올때 별명 설정
import math as m

In [8]:
# dir(모듈이름): 모듈 내에 있는 여러가지 데이터, 함수 등 확인

In [10]:
#모듈 만들기-처음에 모듈명, 함수에 대한 설명 쓰기
'''
    모듈명 : module_test
    mean : 리스트 평균
    caic : 두 수의 사친연산 결과
'''
#리스트 평균 구하는 함수
def mean(lists):
    return sum(lists)/ len(lists)

#두 수의 사칙연산 결과를 구하는 함수
def calc(x, y):
    add=x+y
    sub=x-y
    mult=x*y
    div=x/y
    return add, sub, mult, div

# numpy
- 과학 계산과 데이터 분석에 필요한 기본 패키지
- 다차원 배열(ndarray)을 처리하는 필요한 여러 유용한 기능 제공
    - 같은 자료형의 데이터를 담을 수 있는 포괄적인 배열
    -다차원 배열의 모든 원소는 같은 자료형만 사용 가능
    - 배열의 차원을 rank라 하고, 각 차원의 크기를 튜플로 표시하는 것을 shape 라고함
    -행이 2이고 열이 3인 2차원 배열에서 rank는 2이고 shape는 (2,3)이 됨
    
- 데이터 분선을 위해서는 pandas 와 함께 필수적으로 숙지해야 하는 패키지
- numpy를 사용하는 이유
    - 성능:파이썬 리스트보다 빠름
    - 내장함수: 선형대수, 통계관련 여러 함수가 내장되어 있음
-관행적으로 np로 불러옴(import numpy as np)

 ### np.array():입력데이터를 ndarray로 변환
    - np.arange() range함수와 비슷한지만 리스트 대신 ndarray를 반환
    - np.ones():원소가 모두 1인 배열 생성
    - np.zero():원소가 모두 0인 배열 생성
    - np.empty():특정한 초기값 없이 새로운 배열 생성
    - np.full():지정값 원소로 하여 배열 생성
    - np.eye(),np.identity():단위 행렬 생성
    - np.linespace():처음과 끝 사이의 값을 개수만큼 생성하여 배열로 반환

In [12]:
import numpy as np

In [30]:
np.array(range(7))
np.array([range(5),range(5)])
np.arange(5)
np.arange(1,7,2)
np.ones((4,5)) #(행,열)
np.zeros((2,3,4,5)) #(개수?. 묶음?, 행, 열)
np.empty((3,4), dtype =int)
np.full((2,3,4),5) #5로 채워진 행렬 만들기
np.eye(3) # 3행3렬 단위행렬 만들기
np.identity(3)# 3행3렬 단위행렬 만들기
np.linespace(1, 10 , 2) #1과 10 사이에 잇는 숫자 같은간격으로 2개로 나눔 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [34]:
np.random.rand(3, 4, 5) #rnad()함수는 0,1사이의 랜덤한 ndarray 생성
np.random.randint(1,100,size=(3)) #randint() 함수는 특정 정수 사이에서 랜덤하게 샘플링함
np.random.seed(23) #랜덤한 값을 동일하게 다시 생성하고자 할 때 사용 시작점을 설정해야함
np.random.randn(3,4) #randn(): 정규 분포 이룸
x=np.array([1,2,3,4,5])
np.random.choice(x,(3,4)) #주어진 1차원 ndarray로 부터 랜덤으로 샘플링
np.random.choice(100,size =(3,4))#정수가 주어진 경우는 np.arange(정수)로 간주

array([[3, 2, 4, 2],
       [4, 5, 2, 2],
       [5, 4, 4, 5]])

## 범용함수
    - add():두 배열의 같은 위치의 원소의 합계
    - subtract():두 배열의 같은 위치의 원소의 차
    - multiply():두 배열의 같은 위치의 원소의 곱
    - divide(): 두 배열의 같은 위치의 원소의 나누기
    - floor_divide():나눗셈의 몫만 반환
    - power():두 배열의 같은 위치의 원소의 제곱
    - maximum() ,fmax(): 두 배열의 같은 위치의 원소 중에 큰 값 .fmax은 NaN 무시
    - minmum(), fmin() :두 배열의 같은 위치의 원소 중에 작은 값 .fmin은 NaN 무시
    - mod(): 두 배열의 같은 위치의 원소의 나눈 값의 나머지
    - copysign(): 첫 번째 배열의 부호를 두번째 배열의 부호로 바꾸기
    - greatrt(), greater_equal(), less(), less_equal(), equal(), not_equal()
    :두 배열의 같은 위치의 원소 끼리 비교 >,>=,<,<=,=,!=
    - logical_and(), logical_or(), logical_xor:
    두 배열의 같은 위치의 원소의 논리 연산 &,|,^

In [39]:
#ex
x=np.arange(15).reshape(3,5) #reshape():형변환
y=np.random.choice(100,(3,5))
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[21  6 32 98 32]
 [14 31 78 83 80]
 [70 66 82 85 55]]


In [46]:
a=np.add(x,y)
b=np.subtract(x,y)
c=np.multiply(x,y)
d=np.divide(x,y)
print(a)
print(b)
print(c)
print(d)


[[ 21   7  34 101  36]
 [ 19  37  85  91  89]
 [ 80  77  94  98  69]]
[[-21  -5 -30 -95 -28]
 [ -9 -25 -71 -75 -71]
 [-60 -55 -70 -72 -41]]
[[   0    6   64  294  128]
 [  70  186  546  664  720]
 [ 700  726  984 1105  770]]
[[0.         0.16666667 0.0625     0.03061224 0.125     ]
 [0.35714286 0.19354839 0.08974359 0.09638554 0.1125    ]
 [0.14285714 0.16666667 0.14634146 0.15294118 0.25454545]]


## 통계함수
    - sum():배열 전체 또는 특정 축에 대한 원소들의 합계(크기가 0인 배열은 0)
    - mean():배열 전체 또는 특정 축에 대한 원소들의 산술(크기가 0인 배열은 NaN)
    - std(), var(): 배열 전체 또는 특정 축에 대한 원소들의 표준 편차,분산(자유도 지정가능.기본값n)
    - min(), max(): 배열 전체 또는 특정 축에 대한 원소들의 최소값과 최대값
    - argmin(), argmax(): 최소값의 인데스와 최대값의 인덱스
    - cumsum(): 각 원소의 누적합
    - cumprod(): 각 원소의 누적곱

In [49]:
z=np.random.choice(100,(3,5))
print(z)

[[29 42 38  4 93]
 [32 50 85 27 33]
 [91 95 34  0 91]]


In [50]:
np.sum(y)

833

In [52]:
np.mean(z)

49.6

In [55]:
np.var(z)
np.std(z)

31.750695530439433

## 논리값을 이용한 인덱싱
    - ndarray 인덱싱 시, bool리스트를 전달하여 True 인 경우만 필터링
    - 파이썬 논리 연산자인 and, or, not 키워드 사용 불가
     (and->&, or->| 사용)

In [57]:
x= np.random.randint(1,100,10)
print(x)

[ 6  8  5 17 10 57 49 44 63 71]


In [59]:
even_num= x%2  ==0
print(even_num)

[ True  True False False  True False False  True False False]


In [60]:
x[even_num]

array([ 6,  8, 10, 44])

In [62]:
x[(x>30)&(x<60)] #30보다크고 60보다작음

array([57, 49, 44])

## Pandas
- 데이터 분석을 위한 패키지
- pandas는 파일(or URL)로부터 표로 나타낸 데이터를 불러오는 데 가장 접근하기 쉽고 거의 완변한 기능을 제공
- 시리즈(Series),데이터프레임(DataFrame)이라는 구조를  사용하여 서로 다른 형태 및 시계열 데이터의 복잡한 테이블을 다룰 수 있게 해줌
- 데이터핸들링(자르기.빠진 요소 삭제/추가하기, 명칭변경, 합치기 등)과 시각화에 편리
- 관행적으로 pd로 불러옴(import pandas as pd)

In [64]:
import pandas as pd

### Series
- Series는 Pandas의 기본 객체 중 하나
- Numpy의 ndarray를 기반인덱싱 기능을 추가하여 1차원 배열을 나타냄
- 즉, index와 value가 존재하며, index와 value로 구성된다는 점에서 value만 갖는 list와 구분됨
- index는 기본값으로 0, 1, 2, 3,... 으로 자동생성
- 같은 타입의 0개 이상의 데이터를 가질 수 있음

In [75]:
#Series생성
pd.Series([1,2,3])
#ndarray 이용
import numpy as np
import pandas as pd
pd.Series(np.arange(100))
#data와 index 함께 생성
pd.Series([1,2,3],[10,20,30])
# 인덱스보기, 데이터보기, 인덱스의 데이터 값 보기, 편집
s=pd.Series([1,2,3],[10,20,30])
s.index
s.values
s[10]
s[10]=5
s

10    5
20    2
30    3
dtype: int64

# Series 분석

In [77]:
s= pd.Series([1,2,3,4,5,1,2,3,4,np.NaN])

In [80]:
s.size #개수 표현
len(s) #개수 표현
s.shape#튜플안에 개수 표현
s.unique() #중복되는 것들 지우고 표현
s.count() #NaN값 제외하고 개수 표현
s.mean() #NaN값 제외한 평균<- np.array일경우 난값이 있으면 답은 nan으로 나옴 ->Series로 형변환
s.value_counts() #범주별로 몇개 있나 확일 할 때 사용 NaN 제외 
s.head() #앞에부터 ()안의 수만큼 봄 빈칸이면 5개
s.tail() #뒤에부터 ()안의 수만큼 봄 빈칸이면 5개

2.7777777777777777

In [81]:
# index기준의 연산 -동일 인덱스 갖는 값은 연산 but 각각 갖고 있는건 NaN
s1 = pd.Series([1,2,3,4,5], ['a','b','c','d','x'])
s2 = pd.Series([9,6,3,2,1], ['d','c','b','a','y'])
s1+s2
s1*s2
s1**s2

a         1.0
b         8.0
c       729.0
d    262144.0
x         NaN
y         NaN
dtype: float64

In [82]:
#논리값을 이용한 Series 인덱싱
s =pd.Series([1,0,3,1,0,2,5,4,3,np.NaN])
s

0    1.0
1    0.0
2    3.0
3    1.0
4    0.0
5    2.0
6    5.0
7    4.0
8    3.0
9    NaN
dtype: float64

In [83]:
s>3 #True False로 표시

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8    False
9    False
dtype: bool

In [84]:
s[s>3] #값을 보려면

6    5.0
7    4.0
dtype: float64

In [89]:
s.index>5 #(index값이 5보다 큰거를 bool형태로 array안에 표시)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [90]:
s[s.index>5] #값을 보려면

6    5.0
7    4.0
8    3.0
9    NaN
dtype: float64

In [86]:
s[(s>3) & (s<5)] #and

7    4.0
dtype: float64

In [87]:
(s>=3).sum() #3보다 크거나 같은 값들의 개수

4

In [88]:
(s[s>=3]).sum() #3보다 크거나 같은 값들의 합

15.0

### Series 변경과 슬라이싱

In [94]:
s= pd.Series(np.arange(10,20,2),['a','b','c','d','e'])
s

a    10
b    12
c    14
d    16
e    18
dtype: int32

In [95]:
#데이터 변경
s['a'] =20
s

a    20
b    12
c    14
d    16
e    18
dtype: int32

In [97]:
#데이터 추가
s['x']= 30
s

a    20
b    12
c    14
d    16
e    18
x    30
dtype: int64

In [98]:
#두개 한번에 수행하려면 리스트형태로 넣기
s[['a','b']]=[100,100]
s

a    100
b    100
c     14
d     16
e     18
x     30
dtype: int64

In [103]:
#삭제 drop()사용
print(s.drop('a'))

b    100
c     14
d     16
e     18
x     30
dtype: int64


In [105]:
#슬라이싱
s[1:3] #1번부터 2번인덱스까지
s['a':'b'] #익데스 a부터 b까지

a    100
b    100
dtype: int64

### Data Frame
- DataFrame은 Series와 같은 일련의 객체를 하나의 칼럼이나 여러 개의 칼럼으로 구성하는 데이터 구조
    - series가 1차원이라면 DataFrame은 2차원으로 확대된 버전
    - 엑셀과 같이 숫자, 문자 등 다양한 데이터를 하나의 표(table)에 담을 수 있는 자료 구조
- 2차원이기 때문에 인덱스가 row(행), column(열)으로 구성됨
    - row는 각 개별 데이터를, column은 개별 속성을 의미
    - 각 열은 서로 다른 자료형(숫자형,문자형)이 될 수 있고 열이름, 행이름을 가짐
- Data Analysis, Machine Learning에서 data 변형을 위해 가장 많이 사용됨

In [110]:
import pandas as pd

In [106]:
# DataFrame 생성(dictionary 이용)
fruit = {"name":["apple","banana","lemon"],
        "price": [2500, 3800, 1200] ,
        "num": [5, 3, 10]}
print(fruit)
type(fruit)

{'name': ['apple', 'banana', 'lemon'], 'price': [2500, 3800, 1200], 'num': [5, 3, 10]}


dict

In [107]:
df_fruit =pd.DataFrame(fruit)
print(df_fruit)
df_fruit

     name  price  num
0   apple   2500    5
1  banana   3800    3
2   lemon   1200   10


name  price  num
0   apple   2500    5
1  banana   3800    3
2   lemon   1200   10

In [108]:
# DataFrame 생성(Series 이용)
s1 =pd.Series([10,20,30], ['a','b','d'])
s2 =pd.Series([11,21,31], ['a','b','k'])
s3 =pd.Series([12,22,32], ['a','b','c'])

In [ ]:
print(s1)
print(s2)
print(s3)

In [109]:
df = pd.DataFrame([s1,s2,s3], index=[1,2,3])
df

a     b     d     k     c
1  10.0  20.0  30.0   NaN   NaN
2  11.0  21.0   NaN  31.0   NaN
3  12.0  22.0   NaN   NaN  32.0

In [114]:
#DataFrame 생성(Csv 이용)
train=pd.read_csv("train.csv")
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [117]:
#;이용한 구분
redwine= pd.read_csv("wine_red.csv", sep=";") 
redwine

pH  alcohol  quality
0   3.51      9.4        5
1   3.20      9.8        5
2   3.26      9.8        5
3   3.16      9.8        6
4   3.51      9.4        5
..   ...      ...      ...
95  3.85     12.9        6
96  3.45     10.7        5
97  3.25      9.2        5
98  3.39      9.8        5
99  3.30      9.0        6

[100 rows x 3 columns]

In [ ]:
#DataFrame의 데이터 파악
train.head() #앞에서 부터 표현 빈칸이면 5개까지
train.tail() #뒤에서 부터 표현 빈칸이면 5개까지
train.index #index 속성
train.colums#colums 속성
train.shape #shape속성 (row,colums)확인
train.info()# 데이터의 컬럼별 타입, 개수 등 정보 확인
train.describe() #descirbe() 숫자형 데이터의 기본 통계값 확인

In [124]:
#원하는 데이터만 추출
# column 만 선택
train["Survived"]
train[['Survived','Name','Sex','Age']]
#row만 선택
train[50:55]
#loc,iloc row 선택 -,사용하며 column 도 선택가능
train.loc[[300,400,500,600]]
train.iloc[[300,400,500,600]]
train.loc[[300,400,500,600],['Survived','Name','Sex','Age']]
train.iloc[[300,400,500,600],[1,3,4,5]] #열 표시하기 위해서 iloc은 인덱스번호 필요

Survived                                               Name     Sex   Age
300         1           Kelly, Miss. Anna Katherine "Annie Kate"  female   NaN
400         1                                 Niskanen, Mr. Juha    male  39.0
500         0                                   Calic, Mr. Petar    male  17.0
600         1  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0

In [125]:
#논리값 이용한 선택
cls = train['Pclass'] ==1 #Pclass가 1인 
age = (train['Age']>=20)&(train['Age']<30) #나이가 20이상 30미만
train[cls & age]  #Pclass가 1이며 나이가 20이상 30미만

PassengerId  Survived  Pclass  \
23            24         1       1   
34            35         0       1   
83            84         0       1   
88            89         1       1   
97            98         1       1   
102          103         0       1   
118          119         0       1   
139          140         0       1   
151          152         1       1   
290          291         1       1   
310          311         1       1   
336          337         0       1   
341          342         1       1   
356          357         1       1   
369          370         1       1   
370          371         1       1   
373          374         0       1   
377          378         0       1   
393          394         1       1   
430          431         1       1   
484          485         1       1   
498          499         0       1   
539          540         1       1   
607          608         1       1   
627          628         1       1   
641          642         1       1   
681          682         1       1   
708          709         1       1   
710          711         1       1   
724          725         1       1   
730          731         1       1   
742          743         1       1   
782          783         0       1   
889          890         1       1   

                                                 Name     Sex   Age  SibSp  \
23                       Sloper, Mr. William Thompson    male  28.0      0   
34                            Meyer, Mr. Edgar Joseph    male  28.0      1   
83                            Carrau, Mr. Francisco M    male  28.0      0   
88                         Fortune, Miss. Mabel Helen  female  23.0      3   
97                    Greenfield, Mr. William Bertram    male  23.0      0   
102                         White, Mr. Richard Frasar    male  21.0      0   
118                          Baxter, Mr. Quigg Edmond    male  24.0      0   
139                                Giglio, Mr. Victor    male  24.0      0   
151                 Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
290                      Barber, Miss. Ellen "Nellie"  female  26.0      0   
310                    Hays, Miss. Margaret Bechstein  female  24.0      0   
336                         Pears, Mr. Thomas Clinton    male  29.0      1   
341                    Fortune, Miss. Alice Elizabeth  female  24.0      3   
356                       Bowerman, Miss. Elsie Edith  female  22.0      0   
369                     Aubart, Mme. Leontine Pauline  female  24.0      0   
370                       Harder, Mr. George Achilles    male  25.0      1   
373                               Ringhini, Mr. Sante    male  22.0      0   
377                         Widener, Mr. Harry Elkins    male  27.0      0   
393                            Newell, Miss. Marjorie  female  23.0      1   
430         Bjornstrom-Steffansson, Mr. Mauritz Hakan    male  28.0      0   
484                           Bishop, Mr. Dickinson H    male  25.0      1   
498   Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0      1   
539                Frolicher, Miss. Hedwig Margaritha  female  22.0      0   
607                       Daniel, Mr. Robert Williams    male  27.0      0   
627                     Longley, Miss. Gretchen Fiske  female  21.0      0   
641                              Sagesser, Mlle. Emma  female  24.0      0   
681                                Hassab, Mr. Hammad    male  27.0      0   
708                              Cleaver, Miss. Alice  female  22.0      0   
710  Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")  female  24.0      0   
724                     Chambers, Mr. Norman Campbell    male  27.0      1   
730                     Allen, Miss. Elisabeth Walton  female  29.0      0   
742             Ryerson, Miss. Susan Parker "Suzette"  female  21.0      2   
782                            Long, Mr. Milton Clyde    male  29.0      0   
889                   